### ISSUE TITLE
Code Copy not working in iframe

### ISSUE THREAD

**Issue by richard-to** [google/mesop#1023]
Error message:

```
Uncaught (in promise) NotAllowedError: Failed to execute 'writeText' on 'Clipboard': The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.
    at markdown.ts:80:33
    at HTMLElement.<anonymous> (dom_renderer.ts:384:11)
    at _ZoneDelegate.invokeTask (zone.umd.js:447:37)
    at Object.onInvokeTask (core.mjs:15730:33)
    at _ZoneDelegate.invokeTask (zone.umd.js:446:42)
    at ZoneImpl.runTask (zone.umd.js:195:51)
    at ZoneTask.invokeTask [as invoke] (zone.umd.js:529:38)
    at invokeTask (zone.umd.js:1165:22)
    at globalCallback (zone.umd.js:1196:31)
    at HTMLElement.globalZoneAwareCallback (zone.umd.js:1232:20)
```

I tested that the copy button works on the non-iframed site: https://wwwillchen-mesop.hf.space/embed/text_to_text

----

I think this StackOverflow explains it: https://stackoverflow.com/questions/61401384/can-text-within-an-iframe-be-copied-to-clipboard

**Comment by wwwillchen** [comment]
Yeah, I think your explanation makes sure (ran into something similar in colab). Not sure if there's anything we can do on our end?

**Comment by richard-to** [comment]
Yeah probably not much. I think just a few things:

1. Maybe update documentation for markdown/code component to point this out
2. If it's possible, we can update the iframes that we use for the demo site to make enable copy/paste for the code blocks. I think we need to add it to both iframes?
3. Maybe add an option to disable copy code button on the markdown/code components.

**Comment by richard-to** [comment]
Closing this. This is WAI and not related to Mesop itself.
