### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by lingdon1719** [google/mesop#480]
Traceback (most recent call last):
  File "D:\Users\LENOVO\PycharmProjects\github部署\webui\cs.py", line 3, in <module>
    import mesop as me
  File "D:\Users\LENOVO\PycharmProjects\github部署\.venv\lib\site-packages\mesop\__init__.py", line 5, in <module>
    from mesop.colab.colab_run import colab_run as colab_run
  File "D:\Users\LENOVO\PycharmProjects\github部署\.venv\lib\site-packages\mesop\colab\colab_run.py", line 6, in <module>
    from mesop.runtime import enable_debug_mode
  File "D:\Users\LENOVO\PycharmProjects\github部署\.venv\lib\site-packages\mesop\runtime\__init__.py", line 1, in <module>
    from .runtime import (
  File "D:\Users\LENOVO\PycharmProjects\github部署\.venv\lib\site-packages\mesop\runtime\runtime.py", line 6, in <module>
    import mesop.protos.ui_pb2 as pb
ModuleNotFoundError: No module named 'mesop.protos.ui_pb2'

且pip Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
只有mesop-0.0.1-py3-none-any.whl

**Comment by wwwillchen** [comment]
You're using a very old version of mesop.

Try doing:

```sh
pip uninstall mesop
pip install mesop
```
